### ISSUE TITLE
Synology+Docker: Permission problems

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [dictcp/docker-openvscode-server#1]
Trying to deploy it on my Synology DS918+ with Docker via Portainer stack:
```
---
version: '3.3'
services:
    openvscode-server:
        image: ghcr.io/dictcp/openvscode-server
        container_name: openvscode
        ports:
            - 3000:3000
        volumes:
            - /volume1/docker/openvscode:/home/workspace:cached
        labels:
            - deunhealth.restart.on.unhealthy=true
networks:
  default:
    name: dockernet
    external: true
```
I get permission errors and immediate shutdown of said container:

```
[main 2021-10-09T14:18:54.265Z] rejected promise not handled within 1 second: Error: EACCES: permission denied, mkdir '/home/workspace/.openvscode-server'
[main 2021-10-09T14:18:54.271Z] stack trace: Error: EACCES: permission denied, mkdir '/home/workspace/.openvscode-server'
[main 2021-10-09T14:18:54.272Z] [Error: EACCES: permission denied, mkdir '/home/workspace/.openvscode-server'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/workspace/.openvscode-server'
}
```
